#!/usr/bin/bash

set -eoux pipefail
dnf5 versionlock add "qt6-*"

dnf5 -y install \
    git \
    cmake \
    extra-cmake-modules \
    gcc-g++ \
    kf6-kwindowsystem-devel \
    plasma-workspace-devel \
    libplasma-devel \
    qt6-qtbase-private-devel \
    qt6-qtbase-devel \
    kwin-devel \
    kf6-knotifications-devel \
    kf6-kio-devel \
    kf6-kcrash-devel \
    kf6-ki18n-devel \
    kf6-kguiaddons-devel \
    libepoxy-devel \
    kf6-kglobalaccel-devel \
    kf6-kcmutils-devel \
    kf6-kconfigwidgets-devel \
    kf6-kdeclarative-devel \
    kdecoration-devel \
    wayland-devel \
    libdrm-devel \
    rpm-build

git clone https://github.com/xarblu/kwin-effects-better-blur-dx
cd kwin-effects-better-blur-dx
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr
make -j"$(nproc)"
make install
cd /
rm -rf /kwin-effects-better-blur-dx

dnf5 -y remove \
    git \
    cmake \
    extra-cmake-modules \
    gcc-g++ \
    kf6-kwindowsystem-devel \
    plasma-workspace-devel \
    libplasma-devel \
    qt6-qtbase-private-devel \
    qt6-qtbase-devel \
    kwin-devel \
    kf6-knotifications-devel \
    kf6-kio-devel \
    kf6-kcrash-devel \
    kf6-ki18n-devel \
    kf6-kguiaddons-devel \
    libepoxy-devel \
    kf6-kglobalaccel-devel \
    kf6-kcmutils-devel \
    kf6-kconfigwidgets-devel \
    kf6-kdeclarative-devel \
    kdecoration-devel \
    wayland-devel \
    libdrm-devel \
    rpm-build
