#!/usr/bin/bash

set -eoux pipefail

rm -f /opt
mkdir -p /opt

for repo in \
    "https://copr.fedorainfracloud.org/coprs/scottames/ghostty/repo/fedora-${FEDORA_VERSION}/scottames-ghostty-fedora-${FEDORA_VERSION}.repo" \
    "https://copr.fedorainfracloud.org/coprs/lihaohong/yazi/repo/fedora-${FEDORA_VERSION}/lihaohong-yazi-fedora-${FEDORA_VERSION}.repo" \
    "https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-${FEDORA_VERSION}/atim-starship-fedora-${FEDORA_VERSION}.repo" \
    "https://copr.fedorainfracloud.org/coprs/sneexy/zen-browser/repo/fedora-${FEDORA_VERSION}/sneexy-zen-browser-fedora-${FEDORA_VERSION}.repo" \
    "https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo" \
    "https://repository.mullvad.net/rpm/stable/mullvad.repo" \
    "https://copr.fedorainfracloud.org/coprs/yalter/niri-git/repo/fedora-${FEDORA_VERSION}/yalter-niri-fedora-${FEDORA_VERSION}.repo" \
    "https://copr.fedorainfracloud.org/coprs/aflyhorse/libjpeg/repo/fedora-${FEDORA_VERSION}/aflyhorse-libjpeg-fedora-${FEDORA_VERSION}.repo"; do
    dnf5 -y config-manager addrepo --overwrite --from-repofile="$repo"
done
unset -v repo

dnf5 config-manager setopt skip_if_unavailable=1

dnf5 -y install \
    ghostty \
    yazi \
    starship \
    zen-browser \
    brave-browser \
    mullvad-vpn \
    mullvad-browser \
    niri

# Install both stable and beta versions of Bitwig Studio, this could be moved to another file in the future, but depends on libjpeg.so.8 from the copr here.
# It'd be best to separate concerns and have install-bitwig, install-virtualization, etc. files instead of one install-extra. There's not too much here to do that yet.
dnf5 -y install rpm-build
git clone https://github.com/teervo/bitwig-fedora.git
cd bitwig-fedora
./bitwig-rpm.sh || true
dnf5 -y install ./rpmbuild/RPMS/x86_64/bitwig-studio-*.rpm
./bitwig-rpm.sh --beta || true
BETA_DEB=$(ls ./rpmbuild/SOURCES/bitwig-studio-*beta*.deb)
rm -rf /tmp/bitwig-beta
mkdir -p /tmp/bitwig-beta
ar x --output /tmp/bitwig-beta "$BETA_DEB"
tar axf /tmp/bitwig-beta/data.tar.* -C /tmp/bitwig-beta
mv /tmp/bitwig-beta/opt/bitwig-studio /opt/bitwig-studio-beta
ln -sf /opt/bitwig-studio-beta/bitwig-studio /usr/bin/bitwig-studio-beta
install -Dm644 /tmp/bitwig-beta/usr/share/applications/com.bitwig.BitwigStudio.desktop /usr/share/applications/com.bitwig.BitwigStudioBeta.desktop
sed -i -e 's|^Exec=.*|Exec=bitwig-studio-beta|' \
    -e 's|^TryExec=.*|TryExec=bitwig-studio-beta|' \
    -e 's|^Name=.*|Name=Bitwig Studio (Beta)|' \
    -e 's|/opt/bitwig-studio|/opt/bitwig-studio-beta|g' \
    /usr/share/applications/com.bitwig.BitwigStudioBeta.desktop
rm -rf /tmp/bitwig-beta
cd /
rm -rf /bitwig-fedora

# These are in the fedora repos. Keeping these here because they're related to the extra stuff in here.
dnf5 -y install \
    noctalia \
    nu \
    atuin \
    zoxide \
    helix \
    qemu-kvm \
    libvirt \
    virt-manager \
    virt-viewer

systemctl enable libvirtd.service

# Firefox has been replaced with Mullvad and Zen.
dnf5 -y remove \
    rpm-build \
    firefox || true

rm -f /etc/yum.repos.d/*ghostty*.repo \
    /etc/yum.repos.d/*yazi*.repo \
    /etc/yum.repos.d/*starship*.repo \
    /etc/yum.repos.d/*zen-browser*.repo \
    /etc/yum.repos.d/brave-browser.repo \
    /etc/yum.repos.d/mullvad.repo \
    /etc/yum.repos.d/*niri*.repo \
    /etc/yum.repos.d/*libjpg*.repo
